### ISSUE TITLE
Unity SetActiveAnimation and Blending

### ISSUE THREAD

**Issue by EvoKyle** [kestrelm/Creature_Unity#2]
**CreatureRenderer.SetActiveAnimation()** needs to call **creature_manager.SetAutoBlending(false);**, otherwise if you blend two animations, and later call SetActiveAnimation in order to do a non-blending transition, it will loop the previously blended animation improperly (since blending will still be set to true) instead of using the new animation you set.

**Comment by kestrelm** [comment]
Hello,
Thanks for submitting the issue and fix!
The change has been checked in:
https://github.com/kestrelm/Creature_Unity/commit/a7db8ea6d3bd1810c43f15a4a175b20a479d71db
