### ISSUE TITLE
Unity Static Event Triggering

### ISSUE THREAD

**Issue by EvoKyle** [kestrelm/Creature_Unity#3]
In CreatureGameController.cs:
**public static event eventTrigger OnEventTrigger;**

This needs to have the "static" tag removed from it. With static enabled, if you ever have multiple Creature-animated sprites in the scene, you will have events triggering on *all* of them when it's triggered for a single instance. Without static, it properly triggers on a single Creature instance.

**Comment by kestrelm** [comment]
Hello,
Thanks for submitting the issue and fix!
The change has been checked in:
https://github.com/kestrelm/Creature_Unity/commit/a7db8ea6d3bd1810c43f15a4a175b20a479d71db
