### ISSUE TITLE
Unity Animation Event Triggering

### ISSUE THREAD

**Issue by EvoKyle** [kestrelm/Creature_Unity#4]
In the CreatureFrameCallback class, this line:
**if((int)Math.Round(frameIn) >= frameIn)**

needs to be changed to:

**if((int)Math.Round(frameIn) >= frame)**

Otherwise, animation events trigger randomly/sporadically, instead of at the intended time.

**Comment by kestrelm** [comment]
Hello,
Thanks for submitting the issue and fix!
The change has been checked in:
https://github.com/kestrelm/Creature_Unity/commit/a7db8ea6d3bd1810c43f15a4a175b20a479d71db
