### ISSUE TITLE
Overlay Animations

### ISSUE THREAD

**Issue by Lelegithub** [kestrelm/Creature_Unity#5]
Hello! Like most of game studios we have this problem using Creature:
> We have a character with 4 animations : a "Run" animation, a
> "Jump"animation, a "Shoot with Gun" animation and a "Shoot an arrow with
> elbow" animation.
>
> In theory we should make the animation Run( or jump) being OVERWRITTEN by
> the animation " Shoot with gun" JUST for the arms  whenever it happens at
> any time! Usually this is achieved with the Layers in Mecanim in Unity.
> But How Can I manage this situation? You don't have any tuturial about
> it, in your tutorial you simply blend between two animations which is
> almost never the case in games where you need to change the shooting
> weapon.
>
> How can we address this? Thank you very much.

**Comment by kestrelm** [comment]
Added functionality to perform animation blending of mixing of specific bones from other animation clips onto the current bones of the animation clip. See the comments for how to use the new API:
https://github.com/kestrelm/Creature_Unity/commit/201075c290e15d4d9dd39314f060adb99cffac10
