### ISSUE TITLE
 MISSING SetOverrideRegionAlpha for CreaturePACK

### ISSUE THREAD

**Issue by Lelegithub** [kestrelm/Creature_Unity#8]
// Sets an override opacity/alpha value for a region
        public void SetOverrideRegionAlpha(string region_name_in, float value_in)
        {
            region_override_alphas[region_name_in] = value_in;
        }

**Comment by Lelegithub** [comment]
And EVENTS too.

**Comment by kestrelm** [comment]
Code to set Alpha Overrides has been checked in:
https://github.com/kestrelm/Creature_Unity/commit/e506c798057d2ade99bb39bf11243c22ff7e1ca5

For events, it is more time consuming and will be done when I get the cycles. Thanks.
