### ISSUE TITLE
MISSING SetActiveItemSwap(String region_name, int swap_idx)   in CREATURE PACK

### ISSUE THREAD

**Issue by Lelegithub** [kestrelm/Creature_Unity#9]
public void SetActiveItemSwap(String region_name, int swap_idx)
        {
            active_uv_swap_actions[region_name] = swap_idx;
        }

**Comment by kestrelm** [comment]
This is not possible for now since the CreaturePack framework is intended to be a compact representation for Creature playback. It should not contain all functions of the standard Creature runtime, otherwise the performance and size advantages will be gone.
